services:
  barracuda-dhcp-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - INTERFACE=${INTERFACE}
    user: root
    container_name: barracuda-dhcp-server
    tty: true
    network_mode: host
    environment:
      - INTERFACE=${INTERFACE}
    restart: no