services:
  barracuda-dhcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    container_name: barracuda-dhcp-server
    tty: true
    network_mode: host
    cap_add:
      - NET_ADMIN
    dns:
      - 192.168.1.1
    restart: always